version: '3.1'

services:

  image_storage:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z.fips
    environment:
      REMOTE_MANAGEMENT_DISABLE: 1
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    ports:
      - 9000:9000
      - 9001:9001


  database:
    image: mariadb:11-ubi
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  api:
    build:
      context: ../ms-catalog
      dockerfile: ../docker/ms-catalog/Dockerfile

    ports:
      - 8080:8000
    depends_on:
      - database
