/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreadcrumbBar: typeof import('./src/components/BreadcrumbBar.vue')['default']
    CategoryHeader: typeof import('./src/components/CategoryHeader.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HotlinkBar: typeof import('./src/components/HotlinkBar.vue')['default']
    IBi0Circle: typeof import("~icons/bi/0-circle")["default"]
    IBiArrowDownUp: typeof import('~icons/bi/arrow-down-up')['default']
    IBiGrid: typeof import('~icons/bi/grid')['default']
    IBiList: typeof import('~icons/bi/list')['default']
    IBiListUl: typeof import('~icons/bi/list-ul')['default']
    IBiPersonCircle: typeof import("~icons/bi/person-circle")["default"]
    IBiSearch: typeof import("~icons/bi/search")["default"]
    ProfileComponent: typeof import('./src/components/ProfileComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import("./src/components/SearchBar.vue")["default"]
    SortingBar: typeof import('./src/components/SortingBar.vue')['default']
  }
}
