/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreadcrumbBar: typeof import('./src/components/BreadcrumbBar.vue')['default']
    CategoryHeader: typeof import('./src/components/CategoryHeader.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HotlinkBar: typeof import('./src/components/HotlinkBar.vue')['default']
    IBiArrowDownUp: typeof import('~icons/bi/arrow-down-up')['default']
    IBiCartPlusFill: typeof import('~icons/bi/cart-plus-fill')['default']
    IBiGrid: typeof import('~icons/bi/grid')['default']
    IBiList: typeof import('~icons/bi/list')['default']
    IBiListStars: typeof import('~icons/bi/list-stars')['default']
    IBiListUl: typeof import('~icons/bi/list-ul')['default']
    IBiPersonWorkspace: typeof import('~icons/bi/person-workspace')['default']
    IBiQuestionOctagonFill: typeof import('~icons/bi/question-octagon-fill')['default']
    IBiSignDeadEnd: typeof import('~icons/bi/sign-dead-end')['default']
    ProductBox: typeof import('./src/components/ProductBox.vue')['default']
    ProductShelf: typeof import('./src/components/ProductShelf.vue')['default']
    ProfileComponent: typeof import('./src/components/ProfileComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortingBar: typeof import('./src/components/SortingBar.vue')['default']
    SubcategoryListing: typeof import('./src/components/SubcategoryListing.vue')['default']
  }
}
