/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HotlinkBar: typeof import('./src/components/HotlinkBar.vue')['default']
    HotlinkButton: typeof import('./src/components/HotlinkButton.vue')['default']
    IBi0Circle: typeof import('~icons/bi/0-circle')['default']
    IBiList: typeof import('~icons/bi/list')['default']
    IBiPersonCircle: typeof import('~icons/bi/person-circle')['default']
    IBiSearch: typeof import('~icons/bi/search')['default']
    ProfileComponent: typeof import('./src/components/ProfileComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SortingDropdown: typeof import('./src/components/SortingDropdown.vue')['default']
  }
}
