/*
 * This source file was generated by the Gradle 'init' task
 */
package com.microshop.catalog;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class CatalogApplication {
  public static void main(String[] args) {
    var app = new SpringApplication(CatalogApplication.class);
    app.run(args);
  }
}
