### Application properties file

spring.application.name=backend
spring.banner.location=ms-banner.txt
server.port=8080


# Spring DataSource Configuration
# See https://docs.spring.io/spring-boot/reference/data/sql.html#data.sql.datasource.configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/microshop?currentSchema=myschema
spring.datasource.username=microshop
spring.datasource.password=microshop

#spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=https://microshop.us.auth0.com/oauth/token
#spring.security.oauth2.resourceserver.opaquetoken.client-id=57ejyb70FwxOQc1vMDyjlm7YFxxNJqSu
#spring.security.oauth2.resourceserver.opaquetoken.client-secret=Zc51c13OmSdx1ZBdNDpGap3Z8cz0G40AzhxWF-AatK9fUGxNsnX49VnezhxPK-nC
    #spring.security.oauth2.client.registration.okta.client-id=
#spring.security.oauth2.client.registration.okta.client-secret=
#spring.security.oauth2.client.registration.okta.authorization-grant-type=
#spring.securoty.oauth2.client.registration.okta.redirect-uri=
#spring.security.oauth2.client.registration.okta.scope=
#
#spring.security.oauth2.client.registration.provider.okta.authorization-uri=
#spring.security.oauth2.client.registration.provider.okta.token-uri=
