### Application properties file

spring.application.name=backend
spring.banner.location=ms-banner.txt
server.port=8080


# Spring DataSource Configuration
# See https://docs.spring.io/spring-boot/reference/data/sql.html#data.sql.datasource.configuration
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/microshop
spring.datasource.username=microshop
spring.datasource.password=microshop

spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=https://microshop.us.auth0.com/oauth/token
spring.security.oauth2.resourceserver.opaquetoken.client-id=57ejyb70FwxOQc1vMDyjlm7YFxxNJqSu
spring.security.oauth2.resourceserver.opaquetoken.client-secret=***REMOVED***
