repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      # AOSP means that will prettify into Android Open Source Project format.
      # autofix means that will automatically fix encountered not-pretty-formated files.
      - id: pretty-format-java
        args: ["--palantir", "--autofix"]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--src", './sources/ms-webscrapper']
  - repo: local
    hooks:
      - id: biome-check-frontend
        name: biome check frontend
        entry: npx biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types: [text]
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"

        #- repo: https://github.com/biomejs/pre-commit
        #  rev: v0.6.1
        #  hooks:
        #    - id: biome-check
      #additional_dependencies: ["@biomejs/biome@1.4.1"]

        #- repo: https://github.com/pre-commit/mirrors-eslint
        #  rev: 'a135949'  # Use the sha / tag you want to point at
        #  hooks:
        #    - id: eslint
        #      files: \.[jt]sx?$
        #- repo: https://github.com/gherynos/pre-commit-java
        #  rev: v0.6.3  # Use the ref you want to point at
        #  hooks:
        #    - id: pmd
        #      exclude: /test/
        #    - id: cpd
        #      exclude: /test/
        #    - id: checkstyle
        #      exclude: /test/
