version: '3.1'
name: microshop
services:
  #storage_service:
  #  image: minio/minio:RELEASE.2024-10-02T17-50-41Z.fips
  #  environment:
  #    REMOTE_MANAGEMENT_DISABLE: 1
  #    MINIO_ROOT_USER:     ${AWS_ACCESS_KEY}
  #    MINIO_ROOT_PASSWORD: ${AWS_SECRET_KEY}
  #  ports:
  #    - 9000:9000
  #    - 9001:9001

  api_gateway:
    build:
      context: ms-api_gateway
      dockerfile: Dockerfile
    ports:
      - 80:8080
    depends_on:
      - catalog_api
      - image_store
    networks:
      - backend

  mariadb_database:
    image: mariadb:11-ubi
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    #ports:
    #  - 3306:3306
    networks:
      - backend

  image_store:
    build:
      context: ms-image_store
      dockerfile: docker/Dockerfile
    environment:
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      #ports:
      #  - 8080:8080
    depends_on:
      - storage_service
    networks:
      - backend

  ## PORT : 8080
  catalog_api:
    build:
      context: ms-catalog
      dockerfile: docker/Dockerfile
    environment:
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      HTTP_SERVE_PORT: 8080
    depends_on:
      - database
    networks:
      - backend


networks:
  backend:
