/*
 * This source file was generated by the Gradle 'init' task
 */
package com.microshop.api;


import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
//import static org.junit.jupiter.api.Assertions.*;
@SpringBootTest
class AppTest {
    @Test void contextLoads() {
        assertEquals(1, 1);
    }
}

