/*
 * This source file was generated by the Gradle 'init' task
 */
package com.microshop.image_store;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ImageStoreApplication {
  public static void main(String[] args) {
    var app = new SpringApplication(ImageStoreApplication.class);
    app.run(args);
  }
}
