FROM mariadb:11-ubi AS base

# Copy the configs to the container.
#COPY config/microshop.cnf /etc/my.cnf.d/microshop.cnf
#
## Copy the certificates to the container.
#
## Certificate Authority key.
#COPY certificates/ca.pem  /etc/my.cnf.d/certificates/ca.pem
#
## SSL Certificate x509
#COPY certificates/server-cert.pem /etc/my.cnf.d/certificates/server-cert.pem
#
## Server's private key
#COPY certificates/server-key.pem  /etc/my.cnf.d/certificates/server-key.pem
