/*
 * This source file was generated by the Gradle 'init' task
 */
package com.microshop;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {}
}
