
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    ###########################################################################
    ###  MICROSHOP CONFIG BEGIN
    ###########################################################################

    # Set the services here.
    upstream ms-catalog{
        server catalog_api:8080;
    }

    upstream ms-image_store{
        server image_store:8080;
    }

    server{
        listen 80;

        server_name localhost;

        location /image-store{
            ### WARNING!!! This location is responsible for uploading an retrieving images
            ### from the user. So, I'll set a larger max size limit to 100 Megabytes for that proporse.
            client_max_body_size 100M;

            # Redirect /image-store requests to ms-catalog.
            proxy_pass http://ms-image_store;

            # Send these headers for the upstream! (Don't know why) HACK!!!
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /catalog{
            # Redirect /image-store requests to ms-catalog.
            proxy_pass http://ms-catalog;

            # Send these headers for the upstream! (Don't know why) HACK!!!
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    ###########################################################################
    ###  MICROSHOP CONFIG END
    ###########################################################################

    include /etc/nginx/conf.d/*.conf;
}
