### Application properties file

spring.application.name=backend
spring.profiles.active=
spring.banner.location=banner.txt
server.port=${BACKEND_PORT}


# Spring DataSource Configuration
# See https://docs.spring.io/spring-boot/reference/data/sql.html#data.sql.datasource.configuration
spring.datasource.url=jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}
spring.datasource.username=${MARIADB_USERNAME}
spring.datasource.password=${MARIADB_PASSWORD}
