# APPLICATION PROPERTY FILE !!!
# Edit with caution!
spring.application.name=ms-catalog
spring.banner.location=ms-banner.txt

# Port
server.port=8000

#hibernate.check_nullability = true
jakarta.persistence.jdbc.url=jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}

# Spring JPA
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Spring "Datasource"
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}
spring.datasource.username=${MARIADB_USERNAME}
spring.datasource.password=${MARIADB_PASSWORD}

# Logging properties
logging.level.root=warn
logging.level.org.springframework.web=debug
logging.level.org.hibernate=error

# Springdoc Swagger uri (Automatic documentation URL)
springdoc.swagger-ui.path=/docs
