spring.application.name=ms-catalog
spring.banner.location=ms-banner.txt

spring.cloud.aws.region.static=sa-east-1
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.file-size-threshold=10MB
