/*
 * This source file was generated by the Gradle 'init' task
 */
package com.microshop.api;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class CatalogAPIApplication {
    public static void main(String[] args) {
        SpringApplication.run(CatalogAPIApplication.class, args);
    }
}
