/*
 * This source file was generated by the Gradle 'init' task
 */
package com.microshop.webscraper;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        assertNotNull("NOT NULL", "app should have a greeting");
    }
}
