# APPLICATION PROPERTY FILE !!!
# Edit with caution!
spring.application.name=ms-catalog


#hibernate.check_nullability = true
jakarta.persistence.jdbc.url=jdbc:mariadb://127.0.0.1:3306/microshop

# Spring JPA
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Spring "Datasource"
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/microshop
spring.datasource.username=root
spring.datasource.password=root

# Logging properties
logging.level.root=warn
logging.level.org.springframework.web=debug
logging.level.org.hibernate=error

# Springdoc Swagger uri (Automatic documentation URL)
springdoc.swagger-ui.path=/docs

